//! End-to-end JSON-RPC tests against a live Oracle database.
//!
//! Skipped unless `ORACLE_TEST_HOST` is set. The Oracle Instant Client must be
//! loadable, either from the standard library path or from
//! `ORACLE_CLIENT_LIB_DIR` (passed to the plugin through `initialize`).
//!
//! ```bash
//! just demo-db
//! ORACLE_TEST_HOST=127.0.0.1 ORACLE_CLIENT_LIB_DIR=/path/to/instantclient \
//!   cargo test --test live_db -- --test-threads=1
//! ```

use std::io::{BufRead, BufReader, Write};
use std::process::{Child, ChildStdin, ChildStdout, Command, Stdio};

use serde_json::{json, Value};

struct Plugin {
    child: Child,
    stdin: ChildStdin,
    stdout: BufReader<ChildStdout>,
    next_id: u64,
    conn: Value,
}

impl Plugin {
    /// Spawn the plugin and run `initialize`, or return `None` when no test
    /// database is configured.
    fn start() -> Option<Self> {
        let host = std::env::var("ORACLE_TEST_HOST").ok()?;
        let env = |key: &str, default: &str| std::env::var(key).unwrap_or_else(|_| default.into());
        let conn = json!({
            "host": host,
            "port": env("ORACLE_TEST_PORT", "1521").parse::<u16>().expect("ORACLE_TEST_PORT"),
            "database": env("ORACLE_TEST_SERVICE", "FREEPDB1"),
            "username": env("ORACLE_TEST_USER", "system"),
            "password": env("ORACLE_TEST_PASSWORD", "oracle"),
        });

        let mut child = Command::new(env!("CARGO_BIN_EXE_oracle-plugin"))
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .expect("spawn oracle-plugin");
        let stdin = child.stdin.take().unwrap();
        let stdout = BufReader::new(child.stdout.take().unwrap());
        let mut plugin = Plugin {
            child,
            stdin,
            stdout,
            next_id: 0,
            conn,
        };

        let settings = match std::env::var("ORACLE_CLIENT_LIB_DIR") {
            Ok(dir) => json!({ "client_lib_dir": dir }),
            Err(_) => json!({}),
        };
        plugin.call_raw("initialize", json!({ "settings": settings }));
        Some(plugin)
    }

    fn call_raw(&mut self, method: &str, params: Value) -> Value {
        self.next_id += 1;
        let request =
            json!({ "jsonrpc": "2.0", "method": method, "params": params, "id": self.next_id });
        writeln!(self.stdin, "{request}").unwrap();
        self.stdin.flush().unwrap();
        let mut line = String::new();
        self.stdout.read_line(&mut line).unwrap();
        let response: Value = serde_json::from_str(&line).expect("valid JSON-RPC response");
        assert_eq!(response["id"], self.next_id, "response id for {method}");
        response
    }

    /// Call a method with the connection block merged in and return `result`,
    /// failing the test on a JSON-RPC error.
    fn call(&mut self, method: &str, mut params: Value) -> Value {
        params["params"] = self.conn.clone();
        let response = self.call_raw(method, params);
        if let Some(error) = response.get("error") {
            panic!("{method} failed: {error}");
        }
        response["result"].clone()
    }

    fn exec(&mut self, sql: &str) {
        self.call("execute_query", json!({ "query": sql }));
    }
}

impl Drop for Plugin {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

fn names(list: &Value) -> Vec<String> {
    list.as_array()
        .unwrap()
        .iter()
        .map(|v| v["name"].as_str().unwrap().to_string())
        .collect()
}

#[test]
fn metadata_query_and_crud_round_trip() {
    let Some(mut p) = Plugin::start() else {
        eprintln!("ORACLE_TEST_HOST not set; skipping live Oracle test");
        return;
    };
    let schema = p.conn["username"].as_str().unwrap().to_ascii_uppercase();

    assert_eq!(
        p.call("test_connection", json!({})),
        json!({ "success": true })
    );

    // Idempotent fixture: drop leftovers from an aborted run first.
    for stmt in [
        "DROP VIEW TABULARIS_LIVE_V",
        "DROP TABLE TABULARIS_LIVE_ITEMS PURGE",
        "DROP TABLE TABULARIS_LIVE PURGE",
        "DROP FUNCTION TABULARIS_LIVE_FN",
    ] {
        let mut params = json!({ "query": stmt });
        params["params"] = p.conn.clone();
        p.call_raw("execute_query", params);
    }

    p.exec(
        "CREATE TABLE TABULARIS_LIVE (
           ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           NAME VARCHAR2(50) NOT NULL,
           AMOUNT NUMBER(10,2),
           BIG NUMBER(38),
           PAYLOAD CLOB,
           BYTES RAW(4),
           CREATED DATE DEFAULT SYSDATE)",
    );
    p.exec("COMMENT ON TABLE TABULARIS_LIVE IS 'live test table'");
    p.exec("COMMENT ON COLUMN TABULARIS_LIVE.NAME IS 'display name'");
    p.exec(
        "CREATE TABLE TABULARIS_LIVE_ITEMS (
           LIVE_ID NUMBER REFERENCES TABULARIS_LIVE(ID) ON DELETE CASCADE,
           SEQ NUMBER, CONSTRAINT TABULARIS_LIVE_ITEMS_PK PRIMARY KEY (LIVE_ID, SEQ))",
    );
    p.exec("CREATE VIEW TABULARIS_LIVE_V AS SELECT ID, NAME FROM TABULARIS_LIVE");
    p.exec(
        "CREATE OR REPLACE FUNCTION TABULARIS_LIVE_FN(p_x IN NUMBER) RETURN NUMBER AS
         BEGIN RETURN p_x * 2; END;",
    );

    // Metadata.
    let schemas = p.call("get_schemas", json!({}));
    assert!(schemas
        .as_array()
        .unwrap()
        .iter()
        .any(|s| s == &json!(schema)));

    let tables = p.call("get_tables", json!({ "schema": schema }));
    let live = tables
        .as_array()
        .unwrap()
        .iter()
        .find(|t| t["name"] == "TABULARIS_LIVE")
        .expect("TABULARIS_LIVE listed");
    assert_eq!(live["comment"], "live test table");

    let columns = p.call(
        "get_columns",
        json!({ "schema": schema, "table": "TABULARIS_LIVE" }),
    );
    let cols = columns.as_array().unwrap();
    assert_eq!(cols[0]["name"], "ID");
    assert_eq!(cols[0]["is_pk"], true);
    assert_eq!(cols[0]["is_auto_increment"], true);
    assert_eq!(cols[1]["comment"], "display name");
    assert_eq!(cols[1]["is_nullable"], false);

    let fks = p.call(
        "get_foreign_keys",
        json!({ "schema": schema, "table": "TABULARIS_LIVE_ITEMS" }),
    );
    assert_eq!(fks.as_array().unwrap().len(), 1);
    assert_eq!(fks[0]["ref_table"], "TABULARIS_LIVE");

    let indexes = p.call(
        "get_indexes",
        json!({ "schema": schema, "table": "TABULARIS_LIVE_ITEMS" }),
    );
    assert!(!indexes.as_array().unwrap().is_empty());

    assert!(names(&p.call("get_views", json!({ "schema": schema })))
        .contains(&"TABULARIS_LIVE_V".to_string()));
    assert!(names(&p.call("get_routines", json!({ "schema": schema })))
        .contains(&"TABULARIS_LIVE_FN".to_string()));

    let snapshot = p.call("get_schema_snapshot", json!({ "schema": schema }));
    assert!(names(&snapshot).contains(&"TABULARIS_LIVE_ITEMS".to_string()));

    // CRUD with bound values.
    let big = "123456789012345678901234567890";
    p.call(
        "insert_record",
        json!({
            "schema": schema,
            "table": "TABULARIS_LIVE",
            "data": { "ID": 1, "NAME": "alpha", "AMOUNT": 12.5, "BIG": big, "PAYLOAD": "hello" },
        }),
    );
    p.call(
        "insert_record",
        json!({ "schema": schema, "table": "TABULARIS_LIVE", "data": { "ID": 2, "NAME": "beta" } }),
    );
    p.call(
        "update_record",
        json!({
            "schema": schema,
            "table": "TABULARIS_LIVE",
            "pk_map": { "ID": 2 },
            "col_name": "NAME",
            "new_val": "gamma",
        }),
    );

    let result = p.call(
        "execute_query",
        json!({
            "query": "SELECT ID, NAME, AMOUNT, BIG, PAYLOAD FROM TABULARIS_LIVE ORDER BY ID;",
            "limit": 1,
            "page": 1,
        }),
    );
    assert_eq!(
        result["columns"],
        json!(["ID", "NAME", "AMOUNT", "BIG", "PAYLOAD"])
    );
    assert_eq!(result["rows"], json!([[1, "alpha", 12.5, big, "hello"]]));
    assert_eq!(result["pagination"]["has_more"], true);

    let page2 = p.call(
        "execute_query",
        json!({ "query": "SELECT NAME FROM TABULARIS_LIVE ORDER BY ID", "limit": 1, "page": 2 }),
    );
    assert_eq!(page2["rows"], json!([["gamma"]]));

    p.call(
        "delete_record",
        json!({ "schema": schema, "table": "TABULARIS_LIVE", "pk_map": { "ID": 1 } }),
    );
    let remaining = p.call(
        "execute_query",
        json!({ "query": "SELECT COUNT(*) AS N FROM TABULARIS_LIVE" }),
    );
    assert_eq!(remaining["rows"], json!([[1]]));

    // PL/SQL keeps its terminator; the function is callable from SQL.
    let fn_result = p.call(
        "execute_query",
        json!({ "query": "SELECT TABULARIS_LIVE_FN(21) AS X FROM DUAL" }),
    );
    assert_eq!(fn_result["rows"], json!([[42]]));

    // EXPLAIN returns raw `oracle-plan-json` for the TypeScript parser.
    for analyze in [false, true] {
        let plan = p.call(
            "explain_query",
            json!({ "query": "SELECT * FROM TABULARIS_LIVE_V", "analyze": analyze }),
        );
        assert_eq!(plan["engine"], "oracle");
        assert_eq!(plan["format"], "oracle-plan-json");
        let payload: Value = serde_json::from_str(plan["payload"].as_str().unwrap()).unwrap();
        assert_eq!(payload["version"], 1);
        assert_eq!(payload["statistics"], analyze);
        let rows = payload["plan"].as_array().unwrap();
        assert_eq!(rows[0]["id"], 0);
        assert_eq!(rows[0]["operation"], "SELECT STATEMENT");
        assert!(rows
            .iter()
            .any(|row| row["object_name"] == "TABULARIS_LIVE"));
        if analyze {
            assert!(rows.iter().any(|row| row["actual_rows"].is_number()));
        }
    }
    let mut dml = json!({ "query": "DELETE FROM TABULARIS_LIVE", "analyze": true });
    dml["params"] = p.conn.clone();
    assert_eq!(p.call_raw("explain_query", dml)["error"]["code"], -32602);

    p.exec("DROP VIEW TABULARIS_LIVE_V");
    p.exec("DROP FUNCTION TABULARIS_LIVE_FN");
    p.exec("DROP TABLE TABULARIS_LIVE_ITEMS PURGE");
    p.exec("DROP TABLE TABULARIS_LIVE PURGE");
}
